services:
  - type: web
    name: estrapol-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: your-mongodb-uri
      - key: JWT_SECRET
        value: your-secret-key
      - key: NODE_ENV
        value: production